# Chapter 5: Linear Independence

### 5.4 Gram-Schmidt algorithm

The Python implementation of the Gram-Schmidt Algorithm takes as input an array of arrays, *a*.

If the vectors are linearly independent, it returns an array of arrays, *q*, of orthonormal set of computed vectors.

If the vectors are linearly dependent, and the GS Algorithm terminates early at some *q_j = 0*, it returns the array *q[0], ..., q[i-1]* of length *i*.

The following code is supplemented from the Python Companion 5.4 (p. 41,42)

In [2]:
import numpy as np
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
        #Test for dependence
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print('Vectors are linearly dependent.')
            print('GS algorithm terminates at iteration ', i+1)
            return q
        #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print('Vectors are linearly independent.')
    return q

### Book Example - Linearly Independent
(VMLS p.100, Companion p.42)

In [3]:
a = np.array([ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7] ])
q = gram_schmidt(a)
print(q)
#Test orthonormality
print('Norm of q[0] :', (sum(q[0]**2))**0.5)
print('Inner product of q[0] and q[1] :', q[0] @ q[1])
print('Inner product of q[0] and q[2] :', q[0] @ q[2])
print('Norm of q[1] :', (sum(q[1]**2))**0.5)
print('Inner product of q[1] and q[2] :', q[1] @ q[2])
print('Norm of q[2] :', (sum(q[2]**2))**0.5)

Vectors are linearly independent.
[array([-0.5,  0.5, -0.5,  0.5]), array([0.5, 0.5, 0.5, 0.5]), array([-0.5, -0.5,  0.5,  0.5])]
Norm of q[0] : 1.0
Inner product of q[0] and q[1] : 0.0
Inner product of q[0] and q[2] : 0.0
Norm of q[1] : 1.0
Inner product of q[1] and q[2] : 0.0
Norm of q[2] : 1.0


From these results, we see that we have an orthonormal collection of vector q0, q1, snd q2: The norm of each vector is 1, and transposing it with any other vector within the collection yields an inner product of 0. 

### Book Example - Linearly Dependent

(Quiz 5 #5)

The Python companion makes an important mention that you can rig the GS-Algorithm by formulating one of the inserted vectors as a linear combination of the other input vectors. Thus, we would expect the GS-Algorithm to determine that the vectors are linearly dependent - and it does.

In this example, for simplicity, we formulate a third vector as a linear combination of the first and second vector. This is the definition of a linear combination: If any vector can be represented as a linear combination of any other vectors in the set, then the series is **linearly dependent**.

We will use the same input vectors from the previous example, while inputting a third vector as a linear combination of the first vector multiplied by 2 added to the second one.

The algorithm outputs that these vectors are linearly dependent, which is to be expected. Purposefully making the third input vector a linear combination of the first two forces the GS-Algorithm to terminate at the third iteration, the point when it arrives to process the third input vector.

The steps are also written out by hand in a pdf, where we can arrive at the same conclusion.

In [4]:
#The first two vectors
a = np.array([ [-1, 1, -1, 1], [-1, 3, -1, 3]])

#Creating a linearly dependent vector from the above two vectors
lin_dep_vector = 2*a[0] + a[1]

#Create a stacked vector, b, 
b = np.array([a[0], a[1], lin_dep_vector])
q = gram_schmidt(b)
print(q)

Vectors are linearly dependent.
GS algorithm terminates at iteration  3
[array([-0.5,  0.5, -0.5,  0.5]), array([0.5, 0.5, 0.5, 0.5])]


In [5]:
#The 3 vectors from pg 100
a = np.array([ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7]])

q = gram_schmidt(a)
print(q)

Vectors are linearly independent.
[array([-0.5,  0.5, -0.5,  0.5]), array([0.5, 0.5, 0.5, 0.5]), array([-0.5, -0.5,  0.5,  0.5])]


In [6]:
a1 = np.random.randint(-10, 10, size=5)
a2 = np.random.randint(-10, 10, size=5)
a3 = np.random.randint(-10, 10, size=5)
a4 = np.random.randint(-10, 10, size=5)
a5 = np.random.randint(-10, 10, size=5)
print(a1, a2, a3, a4, a5)
a = np.array([ a1, a2, a3, a4, a5 ])
q = gram_schmidt(a)
print(q)

[ -1   9 -10   8 -10] [-3 -2  1  4 -8] [ 9 -4  8 -6 -6] [-7  2  4 -5  0] [ 5  9 -2 -6  4]
Vectors are linearly independent.
[array([-0.05376033,  0.483843  , -0.53760333,  0.43008266, -0.53760333]), array([-0.32364111, -0.50196702,  0.41382501,  0.23413784, -0.64592095]), array([ 0.7809608 ,  0.10566808,  0.20691284, -0.34501855, -0.46592249]), array([-0.51800392,  0.53066379,  0.25962886, -0.58576604, -0.19884389]), array([0.11890514, 0.47027148, 0.65537123, 0.54593839, 0.1927333 ])]


In [7]:
a1 = np.random.randint(-10, 10, size=5)
a2 = np.random.randint(-10, 10, size=5)
a3 = np.random.randint(-10, 10, size=5)
a4 = np.random.randint(-10, 10, size=5)
a5 = np.random.randint(-10, 10, size=5)
a6 = np.random.randint(-10, 10, size=5)
print(a1, a2, a3, a4, a5)
a = np.array([ a1, a2, a3, a4, a5, a6 ])
q = gram_schmidt(a)
print(q)

[-7 -5 -1  8  5] [-5  4  6  4 -5] [ 5 -7  4  5  9] [-7  7  6 -6  6] [-2  5  0  1 -7]
Vectors are linearly dependent.
GS algorithm terminates at iteration  6
[array([-0.54660817, -0.3904344 , -0.07808688,  0.62469505,  0.3904344 ]), array([-0.40007382,  0.41589595,  0.56507601,  0.29836014, -0.50856841]), array([ 0.55543855, -0.19330889,  0.69725065,  0.24880838,  0.32566181]), array([-0.39434474,  0.35169279,  0.28875478, -0.48535149,  0.63392351]), array([ 0.27774214,  0.71661384, -0.32411997,  0.47250994,  0.28461293])]


In [8]:
#The first two vectors
a = np.array([ [6, 1, -6], [1, -9, 10]])

q = gram_schmidt(a)
print(q)

Vectors are linearly independent.
[array([ 0.70224688,  0.11704115, -0.70224688]), array([ 0.54686114, -0.72025614,  0.42681845])]


In [19]:
A = np.array([[1, 2], [0, -2]]) #2 by 3 matrix
B = np.array([[1, 1], [0, -1/2]])
AB = np.matmul(A,B)
BA = np.matmul(B,A)
print("AB")
print(AB)
print("BA")
print(BA)




AB
[[1. 0.]
 [0. 1.]]
BA
[[1. 0.]
 [0. 1.]]


In [ ]:
def back_solve(R, b):
    n = len(b)                      # assign number of unknowns based on b
    x = np.array([0.0] * n)         # solution vector x
    
    # start from last row and move backward to first
    for i in range(n-1, -1, -1):
        # verify that R is upper diagonal
        if R[i][i] == 0:
            return -1
        sum = 0.0
        # evaluate known part of of linear equation at row i
        for j in range (i + 1, n):
            sum += R[i][j] * x[j]
        x[i] = (b[i] - sum) / R[i][i]
    return x

In [14]:
def find_k(A, B):


    # Since A should equal B, we equate the known elements
    if A[0][0] != B[0][0] or A[0][1] != B[0][1] or A[1][0] != B[1][0]:
        print("No solution for k: known elements don't match.")
        return None

    # Solve for k
    k = B[1][1]
    print(f"Value of k is: {k}")
    return k

A = np.array([[4, 1], [4, None]])  # placeholder
B = np.array([[1, 1], [4, -1]])
find_k(A, B)

No solution for k: known elements don't match.
