### Block 1
**The len() function returns the size (dimension)**
This one is pretty straight forward but will be necessary when doing any sort of vector arithmetic as in order to vector sums, multiplication, and inner products, the vectors need to be the same size. So it will always be good to do a check before attempting one of these operations

In [65]:
# block 1, pg. 2
x = [-1.1, 0.0, 3.6, -7.2]
len(x)

4

In [66]:
# additional context/code
def vectorAddition(x_list: list, y_list: list) -> list:
    if len(x_list) == len(y_list):
        xy_list = [] # initialize return list
        for x, y in zip(x_list, y_list): # zip allows iteration over both
            xy_list.append(x + y)
        return xy_list
    else:
        print("List x and y are not the same length")
        return [] # return empty list if can't do vector addition


y = [0, 1, 1, 1]
len(y)

print(vectorAddition(x, y))

[-1.1, 1.0, 4.6, -6.2]


### Block 2
I haven't seen or used number before. Main feature I see is that it can do the linear algebra vector operations, Important to note that it still uses 0 based indices like with other python arrays/lists, and not the linear algebra 1 base indices. 
The book also shows that len works the same, as does index assignment and that -1 is the last element like with normal lists. I wonder if slices work the same?

In [67]:
# block 2, pg. 3
import numpy as np
x = np.array([-1.1, 0.0, 3.6, -7.2])
x[2] # array value at index 2

3.6

In [68]:
print(len(x)) # length of array
x[2] = 20 # list index re-assignment
print(x)
print(x[-1]) # -1 index displays last value
print(x[1:3]) # slices work the same

4
[-1.1  0.  20.  -7.2]
-7.2
[ 0. 20.]


### Block 3
Here the book talks about vector equality. The first example shows basic aliasing. Arrays/lists in python are all passed by reference, so y = x is making it so both variables point to the same object. Numpy uses the same copy method as standard python arrays to do what is called a shallow copy or when two different array objects reference the same elements.

In the first, aliassing, what effects one, effects the other. In a shallow copy they are independent to the other's changes. Other's way to do a shallow copy include slicing and using a constructor, in Numpy's case, I wonder if this will also act the same.

In [69]:
# import numpy as np # I comment out as, as already imported in previous block
x = np.array([-1.1, 0.0, 3.6, -7.2])
y = x # aliassing, x and y now refer to same object
x[2] = 20.0
print(y) # change to x effects y

[-1.1  0.  20.  -7.2]


In [70]:
y[3] = 10
print("x: {}", x) # change to y effects x

z = x.copy() # using copy method as in book, pg. 4
print("z: {}", z)
z[1] = 2 # changing z
print("z: {}", z)
print("x: {}", x) # doesn't effect x

s = z[:] # checking to see if slice method works
print("s: {}", s)
s[3] = -4 # changing s
print("s: {}", s)
print("z: {}", z)  # doesn't effect z

c = np.array(s) # for a list the syntax would be c = list(s), wonder if this works
print("c: {}", c)
c[0] = 100 # changing c
print("c: {}", c)
print("s: {}", s)   # doesn't effect s

x: {} [-1.1  0.  20.  10. ]
z: {} [-1.1  0.  20.  10. ]
z: {} [-1.1  2.  20.  10. ]
x: {} [-1.1  0.  20.  10. ]
s: {} [-1.1  2.  20.  10. ]
s: {} [-1.1  2.  20.  -4. ]
z: {} [-1.1  2.  20.  -4. ]
c: {} [-1.1  2.  20.  -4. ]
c: {} [100.   2.  20.  -4.]
s: {} [-1.1  2.  20.  -4. ]


### Block 4
How numpy does equality is really cool. I believe in normal python arrays it just tests and returns whether the overall array's are the same and doesn't return the individual elements that are true/false. 

In [71]:
# block 4, pg 4
# import numpy as np
x = np.array([-1.1, 0.0, 3.6, -7.2])
y = x.copy()
x == y

array([ True,  True,  True,  True])

In [72]:
# testing how standard array equality works
x = [1, 2, 3, 4]
y = x.copy()
x == y
# just saw that this a block on the next page...

True

### Block 5